=== buturak/buturak.github.io/skos.dtd
<!-- DTD created at Fri Sep 24 13:32:03 CEST 2010 with EditiX. Please insert an encoding attribute header for converting any DTD  -->
<!-- mikael.gunnarsson@hb.se first attempt-->

<!ELEMENT rdf:RDF (skos:ConceptScheme?,skos:Concept*)>
<!ATTLIST rdf:RDF xmlns:dc CDATA #IMPLIED
				xmlns:skos CDATA #IMPLIED
				xmlns:rdf CDATA #IMPLIED>

<!ELEMENT skos:Concept (skos:prefLabel+, (skos:broader | skos:narrower | skos:broaderTransitive | skos:narrowerTransitive | skos:related | skos:definition | skos:scopeNote | skos:example
 | skos:altLabel | skos:hiddenLabel)*)>
<!ATTLIST skos:Concept rdf:about CDATA #REQUIRED>

<!ELEMENT skos:broader EMPTY>
<!ATTLIST skos:broader rdf:resource CDATA #REQUIRED>
<!ELEMENT skos:narrower EMPTY>
<!ATTLIST skos:narrower rdf:resource CDATA #REQUIRED>
<!ELEMENT skos:narrowerTransitive EMPTY>
<!ATTLIST skos:narrowerTransitive rdf:resource CDATA #REQUIRED>
<!ELEMENT skos:broaderTransitive EMPTY>
<!ATTLIST skos:broaderTransitive rdf:resource CDATA #REQUIRED>
<!ELEMENT skos:related EMPTY>
<!ATTLIST skos:related rdf:resource CDATA #REQUIRED>
<!ELEMENT skos:definition (#PCDATA)>
<!ATTLIST skos:definition rdf:resource CDATA #IMPLIED>
<!ELEMENT skos:scopeNote (#PCDATA)>
<!ELEMENT skos:example (#PCDATA)>
<!ATTLIST skos:example rdf:resource CDATA #IMPLIED>
<!ELEMENT skos:prefLabel (#PCDATA)>
<!ATTLIST skos:prefLabel xml:lang CDATA #IMPLIED>
<!ELEMENT skos:altLabel (#PCDATA)>
<!ATTLIST skos:altLabel xml:lang CDATA #IMPLIED>
<!ELEMENT skos:hiddenLabel (#PCDATA)>
<!ATTLIST skos:hiddenLabel xml:lang CDATA #IMPLIED>

<!ELEMENT skos:ConceptScheme (dc:creator | dc:title | dc:description)*>
<!ATTLIST skos:ConceptScheme rdf:about CDATA #REQUIRED>

<!ELEMENT dc:creator (#PCDATA)>
<!ELEMENT dc:title (#PCDATA)>
<!ELEMENT dc:description (#PCDATA)>

=== buturak/buturak.github.io/canids.xml
<?xml version="1.0" encoding="UTF-8"?>
 <!DOCTYPE rdf:RDF SYSTEM "skos.dtd">
<?xml-stylesheet type="text/xsl" href="skos-styleList.xsl"?>
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" 
	xmlns:skos="http://www.w3.org/2004/02/skos/core#" 
	xmlns:dc="http://purl.org/dc/elements/1.1/">
	<skos:ConceptScheme rdf:about="#canids">
		<dc:title>Hunddjur</dc:title>
		<dc:description>Kontrollerad vokabulär för indexering av dokument som handlar om hunddjur.</dc:description>
		<dc:creator>Mikael Gunnarsson</dc:creator>
		<dc:creator>Maria Idebrant</dc:creator>
	</skos:ConceptScheme>
	<skos:Concept rdf:about="#dogs">
			<skos:prefLabel>Hundar
			  </skos:prefLabel>
			  <skos:altLabel>Vovvar
			  </skos:altLabel>
			  <skos:altLabel>Jyckar
			  </skos:altLabel>
			  <skos:altLabel>Byrackor
			  </skos:altLabel>
		<skos:definition>Tama hunddjur som hålls som sällskap, för jakt eller assistans vid nyttodjursskötsel.</skos:definition>
		<skos:broader rdf:resource="#wolves"/>
		<skos:definition rdf:resource="http://sv.wikipedia.org/wiki/Hundar#"/>
		<skos:example rdf:resource="http://sv.wikipedia.org/wiki/Fil:Norwegian_Elkhound.jpg"/>
	</skos:Concept>
	<skos:Concept rdf:about="#wolves">
		<skos:prefLabel>Vargar</skos:prefLabel>
		<skos:altLabel>Ulvar</skos:altLabel>
		<skos:broader rdf:resource="#hunddjur"/>
		<skos:narrower rdf:resource="#dogs"/>
	</skos:Concept>
	<skos:Concept rdf:about="#foxes">
		<skos:prefLabel>Rävar</skos:prefLabel>
		<skos:broader rdf:resource="#hunddjur"/>
		<skos:scopeNote>Avser här även alla underarter, som rödräv, och även fjällräv som annars tillhör ett annat släkte.</skos:scopeNote>
	</skos:Concept>
	<skos:Concept rdf:about="#hunddjur">
		<skos:prefLabel>Hunddjur</skos:prefLabel>
		<skos:narrower rdf:resource="#foxes"/>
		<skos:narrower rdf:resource="#wolves"/>
	</skos:Concept>
</rdf:RDF>

=== buturak/buturak.github.io/annikaeklundskosuppgift.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rdf:RDF SYSTEM "skos.dtd">
<?xml-stylesheet type="text/xsl" href="skos-styleList.xsl"?>
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
  xmlns:skos="http://www.w3.org/2004/02/skos/core#" xmlns:dc="http://purl.org/dc/elements/1.1/">
  <skos:ConceptScheme rdf:about="MyScheme">
    <dc:title>Annika Eklunds Guide till Honsena</dc:title>
    <dc:description>En guide till honsena</dc:description>
    <dc:creator>Annika Eklund</dc:creator>
  </skos:ConceptScheme>
  <skos:Concept rdf:about="#honsochovrigaslagstamfaglar">
    <skos:prefLabel xml:lang="sv">Hons och ovriga slags tamfaglar</skos:prefLabel>
    <skos:altLabel xml:lang="sv">Jyckar</skos:altLabel>
    <skos:altLabel xml:lang="sv">Byrackor</skos:altLabel>
    <skos:narrower rdf:resource="#specificbreedsofchickens"/>
    <skos:definition rdf:resource="http://sv.wikipedia.org/wiki/Hundar#"/>
    <skos:example rdf:resource="http://sv.wikipedia.org/wiki/Fil:Norwegian_Elkhound.jpg"/>
  </skos:Concept>
  <skos:Concept rdf:about="#specificbreedsofchickens">
    <skos:prefLabel>Specific breeds of chickens</skos:prefLabel>
    <skos:narrower rdf:resource="#europeanbreedsofchickens"/>
    <skos:broader rdf:resource="#honsochovrigaslagstamfaglar"/>
  </skos:Concept>
  <skos:Concept rdf:about="#europeanbreedsofchickens">
    <skos:prefLabel>European breeds of chickens</skos:prefLabel>
    <skos:broader rdf:resource="#specificbreedsofchickens"/>
    <skos:narrower rdf:resource="#svenskalanthonsraser"/>
  </skos:Concept>
  <skos:Concept rdf:about="#svenskalanthonsraser">
    <skos:prefLabel xml:lang="sv">Svenska lanthonsraser</skos:prefLabel>
    <skos:altLabel xml:lang="sv">Svenska hons</skos:altLabel>
    <skos:broader rdf:resource="#europeanbreedsofchickens"/>
    <skos:narrower rdf:resource="#bohuslansdalssvarthona"/>
    <skos:definition rdf:resource="#http://www.kackel.se/lantras_hons.html"/>
    <skos:example rdf:resource="http://libris.kb.se/bib/795191"/>
  </skos:Concept>
  <skos:Concept rdf:about="#bohuslansdalssvarthona">
    <skos:prefLabel xml:lang="sv">Bohuslans-Dals svarthona</skos:prefLabel>
    <skos:broader rdf:resource="#svenskalanthonsraser"/>
  </skos:Concept>
  <skos:Concept rdf:about="#gotlandshona">
    <skos:prefLabel xml:lang="sv">Gotlandshona </skos:prefLabel>
  </skos:Concept>
  <skos:Concept rdf:about="#hedemorahona">
    <skos:prefLabel xml:lang="sv">Hedemorahona</skos:prefLabel>
  </skos:Concept>
  <skos:Concept rdf:about="#kindahona">
    <skos:prefLabel xml:lang="sv">Kindahona</skos:prefLabel>
  </skos:Concept>
  <skos:Concept rdf:about="#orusthona">
    <skos:prefLabel xml:lang="sv">Orusthona</skos:prefLabel>
  </skos:Concept>
  <skos:Concept rdf:about="#asbohona">
    <skos:prefLabel xml:lang="sv">asbohona</skos:prefLabel>
  </skos:Concept>
  <skos:Concept rdf:about="#skanskblommehona">
    <skos:prefLabel xml:lang="sv">Skansk blommehona</skos:prefLabel>
  </skos:Concept>
  <skos:Concept rdf:about="#olandshona">
    <skos:prefLabel xml:lang="sv">olandshona</skos:prefLabel>
  </skos:Concept>
  <skos:Concept rdf:about="#olandskdvarghona">
    <skos:prefLabel xml:lang="sv">olandsk dvarghona</skos:prefLabel>
    <skos:altLabel xml:lang="sv">Spitehona</skos:altLabel>
  </skos:Concept>
  <skos:Concept rdf:about="#gammalsvenskdvarghona">
    <skos:prefLabel xml:lang="sv">Gammalsvensk dvarghona</skos:prefLabel>
  </skos:Concept>
  <skos:Concept rdf:about="#bjurholmshona">
    <skos:prefLabel xml:lang="sv">Bjurholmshona</skos:prefLabel>
  </skos:Concept>
</rdf:RDF>
